// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDCs36unUkHrzH55flb33MoAl2fB5JS32U',
    appId: '1:978832393363:web:1dddcb6c8e1d9c06cab966',
    messagingSenderId: '978832393363',
    projectId: 'flutter-notes-1125',
    authDomain: 'flutter-notes-1125.firebaseapp.com',
    storageBucket: 'flutter-notes-1125.firebasestorage.app',
    measurementId: 'G-GZDQ100KVT',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD6U3OyBn8w1Tindbu7n-KWzzgHXPEagpY',
    appId: '1:978832393363:android:b5a599a7f290389bcab966',
    messagingSenderId: '978832393363',
    projectId: 'flutter-notes-1125',
    storageBucket: 'flutter-notes-1125.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAtAaXiJB1lfhpN5ICWoviQVYNIvII5cOc',
    appId: '1:978832393363:ios:fa6426d9a72d8c0ecab966',
    messagingSenderId: '978832393363',
    projectId: 'flutter-notes-1125',
    storageBucket: 'flutter-notes-1125.firebasestorage.app',
    iosBundleId: 'com.example.firebaseNotesApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAtAaXiJB1lfhpN5ICWoviQVYNIvII5cOc',
    appId: '1:978832393363:ios:fa6426d9a72d8c0ecab966',
    messagingSenderId: '978832393363',
    projectId: 'flutter-notes-1125',
    storageBucket: 'flutter-notes-1125.firebasestorage.app',
    iosBundleId: 'com.example.firebaseNotesApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDCs36unUkHrzH55flb33MoAl2fB5JS32U',
    appId: '1:978832393363:web:4a5516bad134a6dacab966',
    messagingSenderId: '978832393363',
    projectId: 'flutter-notes-1125',
    authDomain: 'flutter-notes-1125.firebaseapp.com',
    storageBucket: 'flutter-notes-1125.firebasestorage.app',
    measurementId: 'G-TW3580JPVF',
  );
}
